linters:
  phpcs:
    standard: PSR2
    fixer: true
  csslint: {  }
  tslint: { 
        config: build/tslint.json
  }
  checkstyle:
      config: ./checkstyle.xml  
  flake8:
  phpcs:
    standard: 'PSR2'
    exclude: 'Generic.Files.LineLength,PSR2.Files.EndFileNewline'
    ignore: 'tests/fixtures/generated/*'
    extensions: 'php,ctp'
    tab_width: 4
    fixer: true
  fixer: true
files:
  ignore:
    - 'vendor/*'
    - 'bower_components/*'
    - 'node_modules/*'
fixers:
  enable: true
